# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-08T14:57:58+00:00

from __future__ import annotations
from enum import Enum
from typing import Any
from pydantic import AwareDatetime, BaseModel, Field
from uuid import UUID


class Source(Enum):
    data = "data"
    enrichments = "enrichments"


class Operator(Enum):
    lte = "lte"
    gte = "gte"
    lt = "lt"
    gt = "gt"
    eq = "eq"
    neq = "neq"
    in_ = "in"
    not_in = "not_in"


class ValidationRuleCondition(BaseModel):
    source: Source
    field: str
    operator: Operator
    value: Any


class ValidationRule(BaseModel):
    id: str = Field(..., description="Unique rule identifier")
    description: str | None = Field(
        None, description="Human-readable explanation of the rule"
    )
    source: Source = Field(..., description="Which dict to read the field from")
    field: str = Field(..., description="Field name to evaluate")
    operator: Operator
    value: Any
    condition: ValidationRuleCondition | None = Field(
        None, description="Optional gate — rule only applies when this condition holds"
    )
    message: str = Field(..., description="Message shown when the rule is violated")


class ValidationRules(BaseModel):
    rules: list[ValidationRule]


class RevalidateResult(BaseModel):
    id: UUID
    schema_key: str
    enrichments: dict[str, Any]


class SchemaConfig(BaseModel):
    key: str = Field(
        ..., description='Unique slug (e.g. "receipt", "invoice", "contract")'
    )
    name: str = Field(..., description="Human-readable name")
    description: str | None = None
    tool_schema: dict[str, Any] = Field(
        ..., description="JSON Schema defining fields to extract from the document"
    )
    enrichments_schema: dict[str, Any] | None = Field(
        None,
        description="JSON Schema defining fields that downstream agents will populate",
    )
    system_prompt: str | None = Field(
        None,
        description="Custom system prompt — overrides the default extraction prompt",
    )
    embed_fields: list[str] | None = Field(
        None, description="Field paths to embed for semantic search"
    )
    categorize_fields: list[str] | None = Field(
        None, description='Enrichment fields the LLM fills (e.g. ["category"])'
    )
    validation_rules: ValidationRules | None = Field(
        None, description="Rules evaluated after extraction to determine compliance"
    )


class ExtractionSchema(SchemaConfig):
    id: UUID
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ExtractionResult(BaseModel):
    id: UUID
    schema_key: str
    file_name: str | None = None
    data: dict[str, Any] = Field(
        ..., description="Extracted fields — shape defined by schema.tool_schema"
    )
    enrichments: dict[str, Any] | None = Field(
        None,
        description="Enrichment fields — category, is_compliant, violations, status",
    )
    confidence: float = Field(..., ge=0.0, le=1.0)
    created_at: AwareDatetime


class AgentConfig(BaseModel):
    provider: str = Field(
        ..., description='LLM provider identifier (e.g. "anthropic", "google")'
    )
    model: str = Field(..., description="Model name/ID")


class EmbeddingConfig(BaseModel):
    provider: str = Field(
        ..., description='Embedding provider identifier (e.g. "google", "none")'
    )
    model: str = Field(..., description="Embedding model name")
    dimensions: int = Field(..., description="Embedding vector dimensionality")


class LLMConfig(BaseModel):
    agents: dict[str, AgentConfig] = Field(
        ..., description="Agent name → provider/model config"
    )
    embeddings: EmbeddingConfig


class HealthResponse(BaseModel):
    status: str = Field(..., examples=["ok"])


class HTTPError(BaseModel):
    detail: str
